### ISSUE TITLE
yay installation error

### ISSUE THREAD

**Issue by mrfoxie** [krmanik/Manjaro-Linux-on-Android#15]
# Description
i tried to install yay on manjaro but it gave me this error here is the procedure for it 

# Installation Process
```
sudo pacman -Sy git base-devel -y
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
```
but ended with this error
# Error
```
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

# Screenshot
![Screenshot_20220202-160211_Termux](https://user-images.githubusercontent.com/25217451/152138550-6a91aa30-5bea-4267-a973-758bcfd3017c.png)

**Comment by krmanik** [comment]
Hi,
It is possible to use yay but I haven't build successfully fakeroot. You can try it also.
https://gist.github.com/krmanik/ff2aa651835f1b63a0b954f406013158

I will update it after successful build.

**Comment by krmanik** [comment]
Now, I managed to build `fakeroot-tcp` in manjaro proot.
To install `yay` it requires fakeroot.

## Build fakeroot-tcp
1. Edit `manjaro.sh` file and add `--sysvipc` 
```
nano manjaro.sh
```
![image](https://user-images.githubusercontent.com/12841290/152210857-0a651f69-b391-4b1f-836a-50a862f70dd9.png)

2. Proot into manjaro
```
./manjaro.sh
```

## Build and install fakeroot-tcp
1. Install required packages
```
sudo pacman -S base-devel git
```
2. Git clone fakeroot-tcp package
```
git clone https://aur.archlinux.org/fakeroot-tcp.git
```
3. Change directory to fakeroot-tcp
```
cd fakeroot-tcp
```
4. Remove `prepare()` from PKGBUILD
```
sed -ir '/prepare()/,+6d' PKGBUILD
```
5. Now build it
```
makepkg -irs
```

## Build `yay`
```
sudo pacman -Sy git base-devel -y
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
```

**Comment by mrfoxie** [comment]
> 

thanks this really worked 👍🏻
