### ISSUE TITLE
VNC Viewer displays a black screen

### ISSUE THREAD

**Issue by GnomeDevs** [krmanik/Manjaro-Linux-on-Android#19]
as the title describes, it does that.
![Screenshot_20220419_230905_com realvnc viewer android](https://user-images.githubusercontent.com/73052469/164040044-cfe959ec-4562-4823-8bd9-4213c97e72b6.jpg)
I tried the tigervnc fix but it did not work.

**Comment by krmanik** [comment]
Run this command in proot distro
1. For xfce4
```
startxfce4
```
2. For lxqt
```
startlxqt
```

**Comment by GnomeDevs** [comment]
didn't work 
![Screenshot_20220420_072220_com termux](https://user-images.githubusercontent.com/73052469/164116982-8182ce0c-eafc-4703-8e1b-165cae85fd65.jpg)

**Comment by GnomeDevs** [comment]
now it returns a "no screens found" error
![Uploading Screenshot_20220420_191324_com.termux.jpg…]()

**Comment by GnomeDevs** [comment]
![Uploading Screenshot_20220420_191324_com.termux.jpg…]()

**Comment by GnomeDevs** [comment]
now it returns a "no screens found" error
![Screenshot_20220420_191324_com termux](https://user-images.githubusercontent.com/73052469/164218877-d5322270-eb81-4d40-b044-e0c51a972910.jpg)

**Comment by krmanik** [comment]
`export DISPLAY=:1`

**Comment by krmanik** [comment]
Try these commands
```
export DISPLAY=:1
vncserver
startxfce4
```
All these commands already exists when installation complete. How have you installed the distro?

**Comment by GnomeDevs** [comment]
nope. still doesn't work. or does it?
![Screenshot_20220420_194333_com termux](https://user-images.githubusercontent.com/73052469/164223443-e0c29758-0a28-4f89-b58f-7dadd47c7b9f.jpg)

I installed it according to the readme. don't think I did anything wrong.
should I run ```sudo pacman -S xfce4 xfce4-goodies```
Is it because I did not install Anki? When I tried to do so, it returns a "target not found error.

**Comment by GnomeDevs** [comment]
ran ```sudo pacman -S xfce4 xfce4-goodies``` but it still did not work. nothing changed.

**Comment by GnomeDevs** [comment]
do i need to reinstall the entire thing? the code you asked me to run in the previous reply did not work either.

**Comment by GnomeDevs** [comment]
![Screenshot_20220421_075645_com realvnc viewer android](https://user-images.githubusercontent.com/73052469/164343385-a1d72e3f-2eea-409e-956d-19f220762055.jpg)
![Screenshot_20220421_075625_com termux](https://user-images.githubusercontent.com/73052469/164343393-704f8fa5-311a-4fb1-9b9c-f63bbc510afa.jpg)
better than last time but still not working, I'll try getting xfce4-goodies again

**Comment by GnomeDevs** [comment]
![Screenshot_20220421_080003_com realvnc viewer android](https://user-images.githubusercontent.com/73052469/164343616-25ec5ee6-7e03-497a-8283-2e95be4c9992.jpg)
we're making progress but I don't think it's working as intended
![Screenshot_20220421_080054_com termux](https://user-images.githubusercontent.com/73052469/164343695-10b2be1a-36c8-41e1-a6f1-25a6283abca2.jpg)
mouse input does not work or register

**Comment by GnomeDevs** [comment]
![Screenshot_20220421_080326_com termux](https://user-images.githubusercontent.com/73052469/164343915-b9ce8950-0006-4b8b-a4eb-57895fdc2a38.jpg)

**Comment by GnomeDevs** [comment]
no apps is working, nothing is working
but the basic ui is there

**Comment by GnomeDevs** [comment]
ok managed to get Anki and things, but the mouse input is still not functioning properly or is very laggy to the point it takes too long.

**Comment by GnomeDevs** [comment]
okay, got most things functioning now, but the system is very laggy, is it the ram? can I configure that?

**Comment by GnomeDevs** [comment]
it works now!
