### ISSUE TITLE
Wget doesnt work

### ISSUE THREAD

**Issue by theblobscp** [krmanik/Manjaro-Linux-on-Android#2]
You can't install wget, making the guide pretty much useless

**Comment by infinyte7** [comment]
It may be issues with termux. 
```
pkg install wget
```

Because these commands run in termux.
View https://github.com/termux/termux-app

**Comment by infinyte7** [comment]
Probably this may be the errors
Here is methods to remove errors.
https://github.com/termux/termux-packages/issues/6726

**Comment by theblobscp** [comment]
> pkg install wget

Are you saying this is what I need to do? If so, that doesn't work, as mentioned

**Comment by infinyte7** [comment]
> > pkg install wget
> 
> Are you saying this is what I need to do? If so, that doesn't work, as mentioned

Can you post screenshot of errors?

**Comment by theblobscp** [comment]
Uh I don't have my phone with me rn

**Comment by theblobscp** [comment]
Forgot about this, I kinda quit using it
