### ISSUE TITLE
Pamac broken & sudo fail to work

### ISSUE THREAD

**Issue by GnomeDevs** [krmanik/Manjaro-Linux-on-Android#20]
There were no procedure during the installation for me to set the root password.

**Comment by GnomeDevs** [comment]
Neither Pamac or Sudo were working. I did nothing. This is a fresh install.
![Screenshot_20220422_203422_com termux](https://user-images.githubusercontent.com/73052469/164715235-aea4c1be-757e-4c54-ab05-3031fbe65d4a.jpg)

**Comment by krmanik** [comment]
https://github.com/krmanik/manjaro-fs-arm64/wiki/Faq-%3F#3-not-able-to-run-sudo-commands-

```
chown <username>:<password> /usr/bin/sudo && chmod 4755 /usr/bin/sudo
```
e.g. for username `manjaro` and password `password`, (`:` semicolon in middle)
```
chown manjaro:password /usr/bin/sudo && chmod 4755 /usr/bin/sudo
```

**Comment by GnomeDevs** [comment]
returns the error operation not permitted

**Comment by krmanik** [comment]
This is related issues
https://github.com/krmanik/manjaro-fs-arm64/issues/3

I think it should be username:username. Replace username 

Try it 
```
chown <username>:<usename> /usr/bin/sudo && chmod 4755 /usr/bin/sudo
```

**Comment by GnomeDevs** [comment]
![Screenshot_20220422_233649_com termux](https://user-images.githubusercontent.com/73052469/164747580-49b0f2be-15a0-4cd6-b950-4cd607906983.jpg)
Sudo works now but Pamac still errors. plz help
