### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by TherCN** [krmanik/Manjaro-Linux-on-Android#3]
haven't network
![Screenshot_20210628_231643](https://user-images.githubusercontent.com/85400103/123661244-fd211680-d866-11eb-8db5-33eac2e73f8a.jpg)

**Comment by infinyte7** [comment]
Hi, Try latest version. I have updated it the script will add nameserver to `resolv.conf`

For previous version the following can be done.
In `manjaro/etc/resolv.conf` the namserver should be 8.8.8.8 and 8.8.4.4

Run `cat manjaro/etc/resolv.conf` command in termux. If this not exits then change this.
```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

#### Demo

https://user-images.githubusercontent.com/12841290/126087689-2d840d35-ed3f-44a4-b593-3508ed2a610b.mp4
