### ISSUE TITLE
Vncserver not working

### ISSUE THREAD

**Issue by hdt25** [krmanik/Manjaro-Linux-on-Android#5]

**Comment by infinyte7** [comment]
1. Run `vncpasswd` and set the password
2. Run `vncserver :1` to start it
3. Connect in RealVNC app

It will show error, but it can be connected in RealVNC app.

<img src="https://user-images.githubusercontent.com/12841290/126707070-1e0bf5d2-1d76-499a-a17b-efeb88b68384.gif" height=450px></img>

**Comment by infinyte7** [comment]
tigervnc 1.11.0 have issues.
Try using tigervnc 1.10.1

1. Downgrade 
https://wiki.manjaro.org/index.php/Downgrading_packages

2. Use fix
https://github.com/AndronixApp/AndronixOrigin/blob/master/Pacman/tigervnc-fix.sh

**Comment by infinyte7** [comment]
tigervnc 1.11.0 have issues.
Try using tigervnc 1.10.1

1. Downgrade 
https://wiki.manjaro.org/index.php/Downgrading_packages

2. Download older version of tigervnc from here
http://tardis.tiny-vps.com/aarm/packages/t/tigervnc/

3. Use fix
https://github.com/AndronixApp/AndronixOrigin/blob/master/Pacman/tigervnc-fix.sh
