### ISSUE TITLE
Libreoffice And OpenGl

### ISSUE THREAD

**Issue by hdt25** [krmanik/Manjaro-Linux-on-Android#6]
Can't run libreoffice. Is this manjaro linux support OpenGl?
I had tried ubuntu-kde by Andronix on my phone. It really seems supporting opengl and was able to run 99% Apps. 
What about 'tigervnc-xorg-extensions'
Can we install this in this manjaro.

Your project really helped me. I appreciate your work. But please help to run OpenGl apps on this.![Screenshot_20210724-000135232.jpg](https://user-images.githubusercontent.com/87573085/126826062-1f2a0512-499c-45c0-a02e-e28ab314e052.jpg) 
![Screenshot_20210724-000329566.jpg](https://user-images.githubusercontent.com/87573085/126826290-bba13869-8993-4c1f-9135-e877d98ed1e1.jpg) spinning cube not showing

**Comment by infinyte7** [comment]
Running `libreoffice`
1. Install emcas
`pacman -S emacs`

2. Run 
`emacs /usr/lib/libreoffice/program/oosplash`

3. Search `/proc/version`
4. Change that to this `/prod/version` or anything

<img src="https://user-images.githubusercontent.com/12841290/126849444-8a40b344-357e-4d01-a379-13c11888fded.jpg" height=450px></img>

4. Save it
5. Then create `/prod` folder and `version` file
```
mkdir /prod
cd /prod
nano version
```
Make version remain empty, then `ctrl+o` and `ctrl+x`
5. Now run `libreoffice`


https://user-images.githubusercontent.com/12841290/126850684-0ddcd635-06c3-4c44-aa7f-c4d2fa54e405.mp4

**Comment by infinyte7** [comment]
Now, it is more easy to change the `oosplash` file.

``` 
wget https://raw.githubusercontent.com/infinyte7/manjaro-fs-arm64/main/scripts/fix-libreoffice.py && python fix-libreoffice.py
```
