### ISSUE TITLE
Vnc on other devices

### ISSUE THREAD

**Issue by hdt25** [krmanik/Manjaro-Linux-on-Android#8]
How to access this manjaro linux installed on my phone from vnc viewer on android tv
Please give a solution for that. 
I want to use this awesome thing on my big screen TV . It should be stable to use on TV

**Comment by infinyte7** [comment]
1. Edit config file in .vnc folder
```
nano .vnc/config
```
2. Uncomment `Localhost`
3. Restart vncserver

To connect on another device, find ip address in the termux and put it in another vnc viewer app connected in same network.
1. Find ip address
```
ip addr | grep inet
```
Address will be like 10... Or 192.168...

2. Put that ip address in vncs viewer with password on port 5901,5902... for :1, :2 ...

**Comment by hdt25** [comment]
How to uncomment

**Comment by infinyte7** [comment]
Using `#`

**Comment by hdt25** [comment]
> Using `#`

Give tutorial video

**Comment by infinyte7** [comment]
https://user-images.githubusercontent.com/12841290/132702344-0efae888-08cb-4823-9253-7aa0d74760f0.mp4

**Comment by infinyte7** [comment]
**Connect both devices in same WiFi network**

1. Edit config
```
cd 
cd .vnc
nano config
```
2.  Comment out Localhost, by adding `#` before it
```
Desktop=manjaro
Geometry=1024x768
SecurityTypes=VncAuth,TLSVnc
#Localhost
```
3. Restart vncserver
4. Get ip address
```
ip addr | grep inet
```
5. Put ip address with port in RealVNC viewer 


https://user-images.githubusercontent.com/12841290/132706431-0f082ac2-a8c6-4f2e-9111-169d837e0ad1.mp4

**Comment by rizkihrp** [comment]
for me the problem is on the vncserver-start in /usr/local/bin because it's contain localhost

just write nano /usr/local/bin/vncserver-start

change to this and save

#!/usr/bin/env bash

export USER=$USER
export HOME=$HOME

vncserver -name remote-desktop :1
